# Generated by Django 4.1.6 on 2023-02-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('lat', models.CharField(max_length=60)),
                ('lon', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('food_type', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('cover_img', models.CharField(max_length=200, unique=True)),
                ('alt_text', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=60)),
                ('lon', models.CharField(max_length=60)),
                ('alcoholic_drinks', models.BooleanField()),
                ('has_happy_hour', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('alt_text', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='Apres_Ski_API.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(max_length=60, null=True)),
                ('monday', models.CharField(max_length=60, null=True)),
                ('tuesday', models.CharField(max_length=60, null=True)),
                ('wednesday', models.CharField(max_length=60, null=True)),
                ('thursday', models.CharField(max_length=60, null=True)),
                ('friday', models.CharField(max_length=60, null=True)),
                ('saturday', models.CharField(max_length=60, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour', to='Apres_Ski_API.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(max_length=60, null=True)),
                ('monday', models.CharField(max_length=60, null=True)),
                ('tuesday', models.CharField(max_length=60, null=True)),
                ('wednesday', models.CharField(max_length=60, null=True)),
                ('thursday', models.CharField(max_length=60, null=True)),
                ('friday', models.CharField(max_length=60, null=True)),
                ('saturday', models.CharField(max_length=60, null=True)),
                ('special', models.CharField(max_length=200, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happyhour', to='Apres_Ski_API.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibe', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('favorites', models.BooleanField()),
                ('restaurant', models.ManyToManyField(related_name='engagement', to='Apres_Ski_API.restaurant')),
                ('user', models.ManyToManyField(to='Apres_Ski_API.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('restaurant', models.ManyToManyField(related_name='comment', to='Apres_Ski_API.restaurant')),
                ('user', models.ManyToManyField(to='Apres_Ski_API.user')),
            ],
        ),
    ]
